version: 2

jobs:

  build:

    docker:
      - image: circleci/node:latest

    working_directory: ~/work

    steps:
      - checkout

      - restore_cache:
          key: dependencies_{{ checksum "package.json" }}

      - run:
          name: NPM Install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies_{{ checksum "package.json" }}

      - run:
          name: Run Linter (eslint)
          command: ./node_modules/eslint/bin/eslint.js ./

