version: 2

jobs:

  build:

    docker:
      - image: circleci/node:latest

    working_directory: ~/work

    steps:
      - checkout

      - restore_cache:
          key: dependencies_{{ checksum "package.json" }}

      - run:
          name: NPM Install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies_{{ checksum "package.json" }}

      - run:
          name: Versions
          command: docker --version
          command: ndoe --version
          command: npm --version

      - run:
          name: Run Linter
          # command: npm run list
          command: ./node_modules/eslint/bin/eslint.js ./

      - run:
          name: Run Unit Tests
          # command: npm run test
          command: ./node_modules/mocha/bin/mocha --colors ./test/unit-test/

      - run:
          name: Docker login to QUAY
          command: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}" quay.io

