version: 2

jobs:

  checkout:
    name: Checkout ???
    machine: true
    steps:
      - checkout
          
  install_npm_packages:
    name: 'Install npm packages'
    machine: true
    requires: checkout
    steps:
      - restore_cache:
          key: branch-???-{{ checksum "package.json" }}

      - run:
          name: 'npm install'
          command: npm install

      - save_cache:
          key: branch-???-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  run_linter:
    name: 'Run linter (eslint)'
    machine: true
    requires: install_npm_packages
    steps:
      - run:
        name: run_linter
        command: ./node_modules/eslint/bin/eslint.js ./

  run_unit_tests:
    name: 'Run Unit Tests'
    machine: true
    requires: install_npm_packages
    steps:
      - run:
          command: 'LOGZIO_TOKEN=NOT_A_VALID_TOKEN ./node_modules/mocha/bin/mocha --colors ./test/unit-test/'

workflows:
  version: 2

  build_test_catalog_deploy:
    jobs:
      - checkout
      - install_npm_packages
      - runt_linter
      - run_unit_tests


