defaults: &defaults
  working_directory: ~/work
  docker:
    - image: circleci/node:latest


version: 2

jobs:


  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: dependencies_{{ checksum "package.json" }}

      - run:
          name: NPM Install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies_{{ checksum "package.json" }}

      - run:
          name: Docker Version
          command: docker --version

      - run:
          name: Node Version
          command: node --version

      - run:
          name: NPM Version
          command: npm --version

      - run:
          name: Run Linter
          # command: npm run list
          command: npx eslint ./

      - persist_to_workspace:
          root: .
          paths:
            - .


  run_unit_tests:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Run Unit Tests
          # command: npm run test
          command: npm test
          filters:
            branches:
              only: test


  build_and_catalog_docker_image:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Docker login to QUAY
          command: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin quay.io


          
workflows:
  version: 2

  handle_test_branch:
    jobs:

      - build

      - run_unit_tests:
          requires:
            - build
          filters:
            branches:
              only: test

      - build_and_catalog_docker_image:
          requires:
            - run_unit_tests
          filters:
            branches:
              only: test
